# all the configuration of a user should go into the respective username


pavankumar :
  # unique id for your computer
  "66002175793550" :  # run `import uuid; str(uuid.getnode())` to get this unique id based on computer"s mac address
    figer_type_senses :
      "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/\
      datalessFNER/resources/figer_type_senses.yaml"
    figer_hierarchy :
      "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/\
      datalessFNER/resources/figer_hier.yaml"
    figer_test_json :
      "/Users/pavankumar/Developer/NLPResearch/NER/\
      FNER/data/ner-datasets/Wiki/test.json"
    figer_path : "/Users/pavankumar/Developer/NLPResearch/figer/aaai/exp.label"
    nsd_cache_path :
      "/Users/pavankumar/Developer/NLPResearch/NER/\
      Annotation/datalessFNER/cache/nsd.pkl"
    embeddings_path :
      "/Users/pavankumar/Developer/NLPResearch/embeddings/\
      google/GoogleNews-vectors-negative300.combined_500k.txt"
    synset_offset_pos_embeddings_path :
      "/Users/pavankumar/Developer/NLPResearch/NER/\
      Annotation/finer_annotation/synset_embeddings_300.txt"
    ontonotes_train_path : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/ontonotes-data/Train.name"
    ontonotes_dev_path : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/ontonotes-data/Dev.name"
    ontonotes_train_and_dev_path : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/ontonotes-data/TrainAndDev.name"
    ontonotes_test_path : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/ontonotes-data/Test.name"
    mention_to_type_dist: "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/datalessFNER/resources/mention_to_type_dist.txt.gz"
    figer_type_to_alias : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/finer_annotation/type_to_alias.txt"
    ontonote_to_figer_map : "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/datalessFNER/resources/ontonote_to_figer_type.yaml"
    lsi_model_path : "/Users/pavankumar/Developer/NLPResearch/NER/FNER/cache/lsi_model_100k/wiki_en_lsi_%s.model"
    lda_model_path : "/Users/pavankumar/Developer/NLPResearch/NER/FNER/cache/lda_model_100k/wiki_en_lda_%s.model"
    tfidf_model_path : "/Users/pavankumar/Developer/NLPResearch/NER/FNER/cache/wiki_preprocessed/wiki_en.tfidf_model"


muddire2 :
  # dickens config
  "22095312515053" :
    figer_type_senses : "/home/muddire2/nlpresearch/datalessFNER/resources/figer_type_senses.yaml"
    figer_hierarchy : "/home/muddire2/nlpresearch/datalessFNER/resources/figer_hier.yaml"
    figer_test_json : "/home/muddire2/nlpresearch/ner-datasets/Wiki/test.json"
    figer_path : "/home/muddire2/nlpresearch/figer/aaai/exp.label"
    nsd_cache_path : "/home/muddire2/nlpresearch/datalessFNER/cache/nsd.pkl"
    embeddings_path : "/save/muddire2/GoogleNews-vectors-negative300.combined_500k.txt"
    synset_offset_pos_embeddings_path : "/home/muddire2/nlpresearch/finer_annotation/synset_embeddings_300.txt"
    ontonotes_train_path : "/home/muddire2/nlpresearch/NER/Ontonotes/data/Ontonotes/ColumnFormat/Train.name"
    ontonotes_dev_path : "/home/muddire2/nlpresearch/NER/Ontonotes/data/Ontonotes/ColumnFormat/Dev.name"
    ontonotes_train_and_dev_path : "/home/muddire2/nlpresearch/NER/Ontonotes/data/Ontonotes/ColumnFormat/TrainAndDev.name"
    ontonotes_test_path : "/home/muddire2/nlpresearch/NER/Ontonotes/data/Ontonotes/ColumnFormat/Test.name"
    mention_to_type_dist: "/home/muddire2/nlpresearch/datalessFNER/resources/mention_to_type_dist.txt.gz"
    figer_type_to_alias : "/home/muddire2/nlpresearch/finer_annotation/type_to_alias.txt"
    ontonote_to_figer_map : "/home/muddire2/nlpresearch/datalessFNER/resources/ontonote_to_figer_type.yaml"
    lsi_model_path : "/home/muddire2/nlpresearch/FNER_bk/cache/lsi_model_100k/wiki_en_lsi_%s.model"
    lda_model_path : "/home/muddire2/nlpresearch/FNER_bk/cache/lda_model_100k/wiki_en_lda_%s.model"
    tfidf_model_path : "/home/muddire2/nlpresearch/FNER_bk/cache/wiki_preprocessed/wiki_en.tfidf_model"


  # bronte/austen config
  "220037194737469" :
    figer_type_senses : "/home/muddire2/nlpresearch2/datalessFNER/resources/figer_type_senses.yaml"
    figer_hierarchy : "/home/muddire2/nlpresearch2/datalessFNER/resources/figer_hier.yaml"
    figer_test_json : "/home/muddire2/nlpresearch2/ner-datasets/Wiki/test.json"
    cache_root: "/home/muddire2/nlpresearch2/datalessFNER/cache"
    nsd_cache_path : "/home/muddire2/nlpresearch2/datalessFNER/cache/nsd.pkl"
    embeddings_path : "/shared/preprocessed/muddire2/Google/GoogleNews-vectors-negative300.combined_500k.txt"
    synset_offset_pos_embeddings_path : "/shared/preprocessed/muddire2/Google/synset_embeddings_300.txt"
    mention_to_type_dist: "/home/muddire2/nlpresearch2/datalessFNER/resources/mention_to_type_dist.txt.gz"
    ontonote_to_figer_map: "/home/muddire2/nlpresearch2/datalessFNER/resources/ontonote_to_figer_type.yaml"
    ontonotes_train_path : "/home/muddire2/nlpresearch2/data/ontonotes/ColumnFormat/Train.name"
    ontonotes_dev_path : "/home/muddire2/nlpresearch2/data/ontonotes/ColumnFormat/Dev.name"
    ontonotes_train_and_dev_path : "/home/muddire2/nlpresearch2/data/ontonotes/ColumnFormat/TrainAndDev.name"
    ontonotes_test_path : "/home/muddire2/nlpresearch2/data/ontonotes/ColumnFormat/Test.name"
    figer_type_to_alias : "/home/muddire2/nlpresearch2/finer_annotation/type_to_alias.txt"
    figer_path : "/home/muddire2/nlpresearch2/figer/aaai/exp.label"
    ontonote_to_figer_map: "/home/muddire2/nlpresearch2/datalessFNER/resources/ontonote_to_figer_type.yaml"
    figer_gold: "/Users/pavankumar/Developer/NLPResearch/NER/Annotation/datalessFNER/python/data/gold_cleaned_figer_test.label"

haowu4 :
  "264800833789999" :
    figer_type_senses : "/home/haowu4/codes/dataless_finer/resources/figer_type_senses.yaml"
    figer_hierarchy : "/home/haowu4/codes/dataless_finer/resources/figer_hier.yaml"
    figer_test_json : null
    nsd_cache_path : "/home/haowu4/codes/dataless_finer/cache/nsd.pkl"
    embeddings_path : "/home/haowu4/data/autoextend/GoogleNews-vectors-negative300.combined_500k.txt"
    synset_offset_pos_embeddings_path : "/home/haowu4/data/autoextend/synset_embeddings_300.txt"
    mention_to_type_dist: "/home/haowu4/codes/dataless_finer/resources/mention_to_type_dist.txt.gz"
    ontonote_to_figer_map: "/home/haowu4/codes/dataless_finer/resources/ontonote_to_figer_type.yaml"
    ontonotes_train_path : ""
    figer_path : "/home/haowu4/codes/dataless_finer/sample_data/exp.label"
    figer_gold : "/home/haowu4/codes/dataless_finer/python/eval_output/gold_cleaned_figer_test.label"
    w2v_dict : "/home/haowu4/data/ontonotes_model/w2v_dict"
    w2v_mean : "/home/haowu4/data/ontonotes_model/w2v_mean"
    ontonote-lex : "/home/haowu4/data/ontonotes_model/lex.pkl"
    ontonote-lex-type : "/home/haowu4/data/ontonotes_model/type_lex.pkl"
    ontonote-model : "/home/haowu4/data/ontonotes_model/logreg.pkl"
    ontonotes_train_and_dev_path : "/home/haowu4/data/ontonotes_ner/ColumnFormat/train_and_dev.col"
    ontonotes_test_path : "/home/haowu4/data/ontonotes_ner/ColumnFormat/test.col"